# fly.toml app configuration file generated for buddie-server on 2024-06-22T11:06:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'buddie-server'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
